### ISSUE TITLE
Bring Autogen Agent implementations!!

### ISSUE THREAD

**Issue by joslat** [kbeaugrand/SemanticKernel.Assistants#14]
Why not too take some code from LittleLittleCloud and implement some of the Autogen abstractions? ;)
PR for the Autogen .NET implementation: https://github.com/microsoft/autogen/pull/924/files

I don't like the handling of multi-model but if we do this first and delegate anything on the models to the kernel there we go... we can start bringing in the ConversableAgent, and all the others, including the super cool implementation of the advanced analysis (self coding skill) implemented with dotnetinteractive and source generators :)

The plan: 
1. We got those abstractions working on this codebase.
2, We bring them to the PR in SK.
3. We bring them into Autogen (once PR of .NET is approved).

**Comment by kbeaugrand** [comment]
@joslat what functional differences do you see between the AutoGen ConversableAgent and the current implementation?

**Comment by joslat** [comment]
let me review that and get back to you...

**Comment by kbeaugrand** [comment]
Please see #18 

I provided a same kind of feature provided by Auto-gen but leveraging on Assistants APIs. 

I have 2 agents: 
- Assistant Agent : He writes python code to solve a problem
- CodeIntepreter: He execute the code provided by the assistant in a sandbox (the sandbox is created by docker, and removed once the execution completed).

I have only 1 specialized plugin for the code execution (which interop Docker), the others are simply prompted assistants...

**Comment by kbeaugrand** [comment]
As we saw, since AutoGen from MS doesn't rely in SK, it's hard to map this approach easily?
Then I realize 2 assistants that works together to provide same kind of feature. 

See [https://github.com/kbeaugrand/SemanticKernel.Assistants?tab=readme-ov-file#autogen](https://github.com/kbeaugrand/SemanticKernel.Assistants?tab=readme-ov-file#autogen) to get more info about how to use it.
