### ISSUE TITLE
Property 'input_parameter' not found on type 'SemanticKernel.Assistants.Models.AssistantModel'.

### ISSUE THREAD

**Issue by seekerofsai** [kbeaugrand/SemanticKernel.Assistants#41]
i get following error when i try to run 
Unhandled exception. (Line: 6, Col: 1, Idx: 340) - (Line: 6, Col: 16, Idx: 355): Property 'input_parameter' not found on type 'SemanticKernel.Assistants.Models.AssistantModel'.

**Comment by kbeaugrand** [comment]
Hi, 

Could you give me a sample of your code that demonstrate this error. 
Also giving me more technical information Version of SK, Version of Assistants, ...?

Regards,

**Comment by seekerofsai** [comment]
Thanks for looking in to the issue. i was trying to run the sample https://github.com/kbeaugrand/SemanticKernel.Assistants/tree/main/samples/01-mathematician 

only changes are the config parameters for azureopenai endpoint, key and model deployments

SK version    <PackageReference Include="SemanticKernel.Assistants" Version="1.6.3" />
<TargetFramework>net8.0</TargetFramework>

**Comment by kbeaugrand** [comment]
@seekerofsai, found that I didn't update the sample and readme in my latest changes.

Please see #42 . I'll fix it soon.

**Comment by seekerofsai** [comment]
Thanks @kbeaugrand appreciate it.

**Comment by kbeaugrand** [comment]
Thank you @seekerofsai for reporting this issue. 
This is now merged, I won't create a release since it only impact the sample and the readme. But feel free to reach me out in case you're facing other issues.
